name: Deployment

on:
  push:
    branches:
      - master
#on:
#  schedule:
#    - cron: "*/5 * * * *"
env:
  BUILD_FILE: temporal-build-.zip

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Build page
        run: echo ${{ env.BUILD_FILE }}
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: Install Packages
#        run: npm install
#      - name: Download Images
#        run: echo 'Images'
#      - name: Build page
#        run: echo '::set-env name=BUILD_FILE::temporal-build-.zip' && echo $BUILD_FILE && npm run build:prod
#        run: echo '::set-env name=BUILD_FILE::temporal-build-.zip' && echo $BUILD_FILE && npm run build:prod
#      - name: Generate zip
#        run: |
#          cd build \
#          zip -r $BUILD_FILE * \
#          mv $BUILD_FILE ..
#      - name: Copy build .zip to irrd geotemporal
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          source: $BUILD_FILE
#          target: "/home/irrd/deploys"
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          port: ${{ secrets.SSH_PORT }}
#          script: unzip /home/irrd/deploys/$BUILD_FILE -d /home/irrd/irrd.org/geotemporal
