name: Deployment

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 11,13,14,15 * * *"
#    - cron: "*/5 * * * *"

env:
  BUILD_FILE: temporal-build-${{ github.sha }}-${{ github.run_id }}.zip

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#      - name: Debug
#        run: echo ${{ env.BUILD_FILE }}
      - name: Install Packages
        run: npm install
      - name: Download Images
        run: |
          echo '${{ secrets.GOOGLE_TOKEN }}' > google-token.json
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google-credentials.json
          npm run images
      - name: Build page
        run: npm run build:prod
      - name: Generate zip
        run: |
          cd build
          zip -r ${{ env.BUILD_FILE }} *
          mv ${{ env.BUILD_FILE }} ..
      - name: Copy build .zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ env.BUILD_FILE }}
          target: "/home/irrd/deploys"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            unzip -o /home/irrd/deploys/${{ env.BUILD_FILE }} -d /home/irrd/irrd.org/geotemporal
            find /home/irrd/deploys/temporal-* -mtime +1 -exec rm {} \;

  test:
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Front-end
        run: echo "Execute puppeteer"
